# Generated by Django 5.2 on 2025-08-25 12:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchange", "0003_delete_exchangeorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeOrder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="User Email")),
                (
                    "give_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Amount of Token Given",
                    ),
                ),
                (
                    "receive_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Amount of Token Received",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Fee Percentage (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Transaction Hash",
                    ),
                ),
                (
                    "give_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_give_token",
                        to="exchange.token",
                        verbose_name="Token Given",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="exchange.pool",
                        verbose_name="Exchange Pool",
                    ),
                ),
                (
                    "receive_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_receive_token",
                        to="exchange.token",
                        verbose_name="Token Received",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Order",
                "verbose_name_plural": "Exchange Orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="orders_exch_status_adc90e_idx"
                    ),
                    models.Index(fields=["email"], name="orders_exch_email_e9f6bd_idx"),
                    models.Index(
                        fields=["created_at"], name="orders_exch_created_2d3f18_idx"
                    ),
                ],
            },
        ),
    ]
