# Generated by Django 5.2 on 2025-09-20 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Network name"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Network shortname"
                    ),
                ),
                (
                    "is_testnet",
                    models.BooleanField(default=False, verbose_name="Is testnet"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Network",
                "verbose_name_plural": "Networks",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="exchange_ne_is_acti_70ad0c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Token name")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="Token shortname"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tokens/",
                        verbose_name="Token image",
                    ),
                ),
                (
                    "decimals",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Decimal places"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="exchange.network",
                        verbose_name="Network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Pool name")),
                (
                    "token1_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Token A reserve",
                    ),
                ),
                (
                    "token2_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Token B reserve",
                    ),
                ),
                (
                    "jetton_address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the liquidity provider token (jetton) contract",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Jetton Address",
                    ),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.3"),
                        help_text="Trading fee percentage (e.g., 0.3000 for 0.3%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Fee rate (%)",
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(
                        blank=True,
                        help_text="Deployed smart contract address in TON blockchain",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="TON Contract Address",
                    ),
                ),
                (
                    "is_contract_deployed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the TON smart contract has been successfully deployed",
                        verbose_name="Contract Deployed",
                    ),
                ),
                (
                    "contract_deployed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the contract was deployed",
                        null=True,
                        verbose_name="Contract Deployed At",
                    ),
                ),
                (
                    "deployment_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if contract deployment failed",
                        null=True,
                        verbose_name="Deployment Error",
                    ),
                ),
                (
                    "is_pool_activated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the pool has been activated (OP_DEPLOY_POOL called)",
                        verbose_name="Pool Activated",
                    ),
                ),
                (
                    "pool_activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the pool was activated",
                        null=True,
                        verbose_name="Pool Activated At",
                    ),
                ),
                (
                    "is_liquidity_added",
                    models.BooleanField(
                        default=False,
                        help_text="Whether initial liquidity has been added to the contract",
                        verbose_name="Initial Liquidity Added",
                    ),
                ),
                (
                    "liquidity_added_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when initial liquidity was added",
                        null=True,
                        verbose_name="Liquidity Added At",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time contract state was synchronized with blockchain",
                        null=True,
                        verbose_name="Last Sync At",
                    ),
                ),
                (
                    "admin_wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="TON wallet address of the pool administrator",
                        max_length=100,
                        null=True,
                        verbose_name="Admin Wallet Address",
                    ),
                ),
                (
                    "usdt_master_address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the USDT jetton master contract",
                        max_length=100,
                        null=True,
                        verbose_name="USDT Master Contract Address",
                    ),
                ),
                (
                    "total_liquidity_additions",
                    models.IntegerField(
                        default=0, verbose_name="Total Liquidity Operations"
                    ),
                ),
                (
                    "total_token1_added",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Total Token1 Added",
                    ),
                ),
                (
                    "total_token2_added",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Total Token2 Added",
                    ),
                ),
                (
                    "first_liquidity_added_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First Liquidity Added At"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, null=True, verbose_name="Admin notes"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "token1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools_as_token1",
                        to="exchange.token",
                        verbose_name="Token A",
                    ),
                ),
                (
                    "token2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools_as_token2",
                        to="exchange.token",
                        verbose_name="Token B",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool",
                "verbose_name_plural": "Pools",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["network", "is_active"], name="exchange_to_network_2f6cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["short_name", "network"], name="exchange_to_short_n_13a3ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("short_name", "network")},
        ),
        migrations.AddIndex(
            model_name="pool",
            index=models.Index(
                fields=["is_active"], name="exchange_po_is_acti_5fe73b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pool",
            index=models.Index(
                fields=["token1", "token2"], name="exchange_po_token1__19fe47_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pool",
            unique_together={("token1", "token2")},
        ),
    ]
