# Generated by Django 5.2 on 2025-09-02 13:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="first_liquidity_added_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="First Liquidity Added At"
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_liquidity_additions",
            field=models.IntegerField(
                default=0, verbose_name="Total Liquidity Operations"
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_token1_added",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=20,
                verbose_name="Total Token1 Added",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_token2_added",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=20,
                verbose_name="Total Token2 Added",
            ),
        ),
    ]
