# Generated by Django 5.2 on 2025-08-03 22:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeOrder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, verbose_name="Email пользователя"
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        max_length=100, verbose_name="Адрес кошелька пользователя"
                    ),
                ),
                (
                    "give_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Количество отдаваемого токена",
                    ),
                ),
                (
                    "receive_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Количество получаемого токена",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Курс обмена"
                    ),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Комиссия (%)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "В обработке"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                            ("failed", "Неудачен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хэш транзакции",
                    ),
                ),
                (
                    "give_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_give_token",
                        to="exchange.token",
                        verbose_name="Отдаваемый токен",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="exchange.pool",
                        verbose_name="Пул обмена",
                    ),
                ),
                (
                    "receive_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_receive_token",
                        to="exchange.token",
                        verbose_name="Получаемый токен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на обмен",
                "verbose_name_plural": "Заявки на обмен",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="exchange_ex_status_a4e84c_idx"
                    ),
                    models.Index(fields=["email"], name="exchange_ex_email_0c64a4_idx"),
                    models.Index(
                        fields=["created_at"], name="exchange_ex_created_5846d5_idx"
                    ),
                ],
            },
        ),
    ]
