# Generated by Django 5.2 on 2025-08-23 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="first_liquidity_added_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when liquidity was first added to this pool",
                null=True,
                verbose_name="First Liquidity Added At",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_liquidity_additions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of times liquidity was added to this pool",
                verbose_name="Total Liquidity Additions",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_token1_added",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                help_text="Total amount of Token A added to pool across all operations",
                max_digits=20,
                verbose_name="Total Token A Added",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="total_token2_added",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                help_text="Total amount of Token B added to pool across all operations",
                max_digits=20,
                verbose_name="Total Token B Added",
            ),
        ),
    ]
