# Generated by Django 5.2 on 2025-08-04 11:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_exchangeorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchangeorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Exchange Order",
                "verbose_name_plural": "Exchange Orders",
            },
        ),
        migrations.RemoveField(
            model_name="exchangeorder",
            name="wallet_address",
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="User Email"),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Exchange Rate"
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="fee_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Fee Percentage (%)"
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="give_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Amount of Token Given",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="give_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_give_token",
                to="exchange.token",
                verbose_name="Token Given",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="exchange.pool",
                verbose_name="Exchange Pool",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="receive_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Amount of Token Received",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="receive_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_receive_token",
                to="exchange.token",
                verbose_name="Token Received",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Order Status",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeorder",
            name="transaction_hash",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Transaction Hash"
            ),
        ),
    ]
