# Generated by Django 5.2 on 2025-08-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_pool_first_liquidity_added_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExchangeOrder",
        ),
    ]
