# Generated by Django 5.2 on 2025-08-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_alter_exchangeorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="activation_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash of the pool activation",
                max_length=100,
                null=True,
                verbose_name="Pool Activation Transaction Hash",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="admin_wallet_address",
            field=models.CharField(
                blank=True,
                help_text="TON wallet address of the pool administrator",
                max_length=100,
                null=True,
                verbose_name="Admin Wallet Address",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="contract_address",
            field=models.CharField(
                blank=True,
                help_text="Deployed smart contract address in TON blockchain",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="TON Contract Address",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="contract_deployed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the contract was deployed",
                null=True,
                verbose_name="Contract Deployed At",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="deployment_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if contract deployment failed",
                null=True,
                verbose_name="Deployment Error",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="deployment_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash of the contract deployment",
                max_length=100,
                null=True,
                verbose_name="Deployment Transaction Hash",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="is_contract_deployed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the TON smart contract has been successfully deployed",
                verbose_name="Contract Deployed",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="is_liquidity_added",
            field=models.BooleanField(
                default=False,
                help_text="Whether initial liquidity has been added to the contract",
                verbose_name="Initial Liquidity Added",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="is_pool_activated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the pool has been activated (OP_DEPLOY_POOL called)",
                verbose_name="Pool Activated",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time contract state was synchronized with blockchain",
                null=True,
                verbose_name="Last Sync At",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="liquidity_added_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when initial liquidity was added",
                null=True,
                verbose_name="Liquidity Added At",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="liquidity_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash of the liquidity addition",
                max_length=100,
                null=True,
                verbose_name="Liquidity Transaction Hash",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="pool_activated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the pool was activated",
                null=True,
                verbose_name="Pool Activated At",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="usdt_master_address",
            field=models.CharField(
                blank=True,
                help_text="Address of the USDT jetton master contract",
                max_length=100,
                null=True,
                verbose_name="USDT Master Contract Address",
            ),
        ),
    ]
